
export const carBrands = [
  { make: 'Acura', models: ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX'] },
  { make: 'Audi', models: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'RS', 'S3', 'S4', 'S5', 'TT'] },
  { make: 'BMW', models: ['2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'i3', 'i8', 'M2', 'M3', 'M4', 'M5', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4'] },
  { make: 'Buick', models: ['Cascada', 'Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal'] },
  { make: 'Cadillac', models: ['ATS', 'CT4', 'CT5', 'CT6', 'CTS', 'Escalade', 'XT4', 'XT5', 'XT6', 'XTS'] },
  { make: 'Chevrolet', models: ['Blazer', 'Bolt EV', 'Camaro', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Express', 'Impala', 'Malibu', 'Silverado', 'Sonic', 'Spark', 'Suburban', 'Tahoe', 'Trailblazer', 'Traverse', 'Trax'] },
  { make: 'Chrysler', models: ['300', 'Pacifica', 'Voyager'] },
  { make: 'Dodge', models: ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Journey'] },
  { make: 'Fiat', models: ['124 Spider', '500', '500L', '500X'] },
  { make: 'Ford', models: ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Mustang', 'Ranger', 'Super Duty', 'Transit'] },
  { make: 'Genesis', models: ['G70', 'G80', 'G90', 'GV80'] },
  { make: 'GMC', models: ['Acadia', 'Canyon', 'Savana', 'Sierra', 'Terrain', 'Yukon'] },
  { make: 'Honda', models: ['Accord', 'Civic', 'Clarity', 'CR-V', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline'] },
  { make: 'Hyundai', models: ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Nexo', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'] },
  { make: 'Infiniti', models: ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'] },
  { make: 'Jaguar', models: ['E-PACE', 'F-PACE', 'F-TYPE', 'I-PACE', 'XE', 'XF', 'XJ'] },
  { make: 'Jeep', models: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'] },
  { make: 'Kia', models: ['Cadenza', 'Forte', 'K5', 'K900', 'Niro', 'Optima', 'Rio', 'Sedona', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'] },
  { make: 'Land Rover', models: ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'] },
  { make: 'Lexus', models: ['ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'] },
  { make: 'Lincoln', models: ['Aviator', 'Continental', 'Corsair', 'MKZ', 'Nautilus', 'Navigator'] },
  { make: 'Maserati', models: ['Ghibli', 'GranTurismo', 'Levante', 'Quattroporte'] },
  { make: 'Mazda', models: ['CX-3', 'CX-30', 'CX-5', 'CX-9', 'Mazda3', 'Mazda6', 'MX-5 Miata'] },
  { make: 'Mercedes-Benz', models: ['A-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Metris', 'S-Class', 'SL', 'SLC', 'Sprinter'] },
  { make: 'Mini', models: ['Clubman', 'Convertible', 'Countryman', 'Hardtop'] },
  { make: 'Mitsubishi', models: ['Eclipse Cross', 'Mirage', 'Outlander', 'Outlander Sport'] },
  { make: 'Nissan', models: ['370Z', 'Altima', 'Armada', 'Frontier', 'GT-R', 'Kicks', 'Leaf', 'Maxima', 'Murano', 'NV', 'Pathfinder', 'Rogue', 'Sentra', 'Titan', 'Versa'] },
  { make: 'Porsche', models: ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'] },
  { make: 'Ram', models: ['1500', '2500', '3500', 'ProMaster'] },
  { make: 'Subaru', models: ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'WRX'] },
  { make: 'Tesla', models: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'] },
  { make: 'Toyota', models: ['4Runner', 'Avalon', 'Camry', 'C-HR', 'Corolla', 'GR Supra', 'Highlander', 'Land Cruiser', 'Mirai', 'Prius', 'RAV4', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris'] },
  { make: 'Volkswagen', models: ['Arteon', 'Atlas', 'Golf', 'Jetta', 'Passat', 'Tiguan'] },
  { make: 'Volvo', models: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'] },
];
